spring:
 application:
  name: currency-conversion-service

server:
  port: 8100

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

forex-service:
  ribbon:
    ListOfServers: localhost:8000, localhost:8001
    eureka:
      enabled: false
client:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList